FROM node:18-bullseye-slim AS build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json tsconfig.*json vite.config.ts index.html yarn.lock /app/
COPY src /app/src/
COPY public /app/public/

RUN pwd && ls \
    && yarn install -s --loglevel warn \
    && yarn run build \
    && rm -rf node_modules \
    && rm -rf src \
    && yarn install -s --omit=dev --loglevel warn \
    && ls -l

FROM nginx:1.24.0-bullseye
COPY --from=build /app/dist /usr/share/nginx/html/interno
COPY ./nginx/nginx_dev.conf /etc/nginx/conf.d/default.conf
RUN chgrp -R root /var/cache/nginx /var/run /var/log/nginx && \
    chmod -R 770 /var/cache/nginx /var/run /var/log/nginx
USER nginx
EXPOSE 3000
CMD ["nginx","-g","daemon off;"]